version: "3.8"

services:
  back-end:
    build:
      context: ./innergy-m9-api
    ports:
      - "3333:3333"
    volumes:
      - ./innergy-m9-api:/app
    expose:
      - '3333'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: innergyDB
    ports:
      - "27017:27017"
  # database:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'innergyDB'
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: 'admin'
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: 'password'
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     - "3306:3306"
  #   expose:
  #     # Opens port 3306 on the container
  #     - '3306'
  #     # Where our data will be persisted
  #   volumes:
  #     - innergy-db:/var/lib/mysql
# Names our volume
# volumes:
#   innergy-db:
