# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  node_version: "15.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node_version }}
    - uses: c-hive/gha-npm-cache@v1
    - name: Install NodeJS dependencies
      run: ls package-lock.json && npm install
    - name: Generate environment file
      run: cp .env.testing .env
    - name: Install Adonisjs/cli
      run: npm install --global @adonisjs/cli
    - name: Generate Adonis app secret key
      run: npx adonis key:generate
    - name: Start MongoDB
      run: sudo systemctl start mongod
    - name: Configure mongodb admin
      run: echo "db.createUser({ \  
                  user:\"root\", \
                  pwd:\"example\", \
                  roles:[ \  
                    { \  
                      role:\"userAdminAnyDatabase\", \
                      db:\"admin\" \
                    } \
                  ] \
                })" | mongo mongo
    - name: Configure mongodb user
      run: echo "db.createUser({ \
                    user:\"root\", \
                    pwd:\"example\", \
                    roles:[ \
                      { \
                        role:\"readWrite\", \
                        db:\"innergyDB\" \
                      } \
                    ], \
                    mechanisms:[ \
                      \"SCRAM-SHA-1\" \
                    ] \
                  })" | mongo mongo/innergyDB -u root -p example --authenticationDatabase admin
    - name: Perform integration test
      run: ls package-lock.json && npm run test
