# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  node_version: "15.x"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node_version }}
    - uses: c-hive/gha-npm-cache@v1
    - name: Install NodeJS dependencies
      run: cd innergy-m9-api/ && ls package-lock.json && npm install
    - name: Generate environment file
      run: cd innergy-m9-api/ && cp .env.example .env
    - name: Generate Adonis app secret key
      run: cd innergy-m9-api/ && npx adonis key:generate
    - name: Perform integration test
      run: cd innergy-m9-api/ && ls package-lock.json && npm run test

